### ISSUE TITLE
toutv: error: argument command: invalid choice: 'login' 

### ISSUE THREAD

**Issue by Extarys** [bvanheu/pytoutv#110]
Hello there!

I installed pytoutv from pip3 and I cannot login using toutv login email@domain.com.
I get `toutv: error: argument command: invalid choice: 'login' `

Trying to run ./setup.py gives me `Sorry, pytoutv needs Python 3.3+` but I have version 3.5 (Running Linux Mint)

Any idea how I can fix this?
It would be awesome to get this running :D

**Comment by Extarys** [comment]
I removed the pip package and added python3 instead of python in the first line of the setup.py. It works!

**Comment by simark** [comment]
The "invalid choice" error was probably because you had an older version of pytoutv.  Note that I've just released 3.0.0 which includes the `login` command.  So it can now be installed using `pip3 install pytoutv`.

About the second problem (pytoutv needs Python 3.3+), I have changed the shebang line in setup.py so that it will always use Python 3.
