### ISSUE TITLE
Enhancement: better cope with network errors

### ISSUE THREAD

**Issue by simark** [bvanheu/pytoutv#50]
Since the dawn of time, mankind has used stress in a constructive manner. It has helped him capture animals for food as well as escape from danger. In modern society, however, sources of stress have become ubiquitous. They are now mostly more a nuisance and a health hazard than an advantage. Using pytoutv should not contribute to elevate our global level of stress. To the contrary, it should be a relaxing and revigorating experience.

It turns out that right now, downloads (at least for me) are relatively frequently interrupted because of various network errors and timeouts. For example, I just got this twice:

    Découverte.S2014E19.Le.Cap.1325kbps.ts   231.1 MiB   137/258 [##################################------------------------------]  53%
    Unknown error: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

This makes downloading a big file (e.g. Découverte in HQ, ~400 megabytes) an unacceptable moment of worrying: will my download reach completion or not?

pytoutv should do either or both of:
1. retry downloading a failed section a few times before concluding that all hope is lost;
2. allow resuming a cancelled/interrupted/failed download.

I am sure that 1 is not too hard to implement., but 2 should be possible as well. I don't know if it would be possible to resume a partial download at the right position using only the partial ts file, or if we'd need an index on the side to remember where we left off.

**Comment by bvanheu** [comment]
Regarding #2, we're already caching data on the filesystem, so adding an index of what have been downloaded seems reasonable. It could be a nice addition to the user experience (you've downloaded E1, E2 and E3 but not E4) as well as let us resume interrupted download.

Maybe there are some headers at the beginning of each TS file that gives the length of the segments.

**Comment by eepp** [comment]
I'm going to look into this.

We could as well download all the parts and decrypt them as individual files, mark them as downloaded in a local cache (since they could also be redownloaded in a different directory), and concatenate all the parts into a single video file.

**Comment by eepp** [comment]
After a first investigation, it looks like the individual segments listed in the M3U8 playlist are just a bunch of MPEG-2 TS packets, each having a [fixed size of 184 bytes](http://www.mikrocontroller.net/attachment/27265/mpeg2ts.pdf), i.e. there's no header for those individual files, which CBFT-DT probably decided to split arbitrarily.

The HTTP `Content-Length` header reports the correct file size, however. But I don't see how this is going to help, as we want to know the sum of _all_ the file sizes before reserving a file on disk with this size (like BitTorrent does), and the only way to know that would be to make _n_ requests for a playlist of _n_ entries.

I still believe the best way to handle multiple connections here (and it still has to be proven that parallel connections actually accelerates the download) is to output individual files and join them at the end. This would also allow resuming: download the segment to memory, and write once completed, so that there's no partial segment written to disk.

**Comment by simark** [comment]
I think the idea about writing multiples small files would be a good idea. Perhaps somewhere like

    ~/.toutv/segments/<some unique content id>/<n>.ts

or would it be better to put it in the download directory? The problem is that the download directory can change.

I guess we would assume that if a <n>.ts file is present, it's because it is complete. There is still a slight probability of the program crashing while in the middle of writing a segment, resulting in an incomplete file that we will treat as complete (which is bad). Should we have some way of verifying the integrity of the data? When we finish donwloading a segment, we could write the md5 (or other) of its data in <n>.md5 and then write the <n>.ts file. When resuming, if we check if the md5 matches the .ts file, if not we discard it and download it again.

**Comment by eepp** [comment]
I'm not sure about the common directory for all segments. I'm not sure that users want to accumulate segments in their home directory. Compare this to downloading a file with a browser or a BitTorrent client: temporary files are always created in the download directory. At least it could be an option.

I agree with the MD5 file technique. In fact we just need a flag at some place. Say the segment file is named `segment3.ts`, we only need to write an empty `segment3.ts.done` file beside, which confirms `segment3.ts` is done, since it's written afterwards. Sure the user could alter `segment3.ts` and leave `segment3.ts.done`, but that's not our problem.

**Comment by simark** [comment]
Actually, we could just do like firefox. Write to segment3.ts.part, and then rename it to segment3.ts. A rename should be atomic enough:

     If successful, the renaming will be an atomic operation (this is a POSIX requirement). [1]

[1] https://docs.python.org/3/library/os.html#os.rename

**Comment by simark** [comment]
Also, given the use case of pytoutv, it's rare enough that you download the same thing twice in a short amount of time. So yeah, it wouldn't be very useful to have a global location for the segments. Let's just put them in a temporary directory next to the destination file.

**Comment by eepp** [comment]
Great.

**Comment by eepp** [comment]
Closing this since automatic download resume is supported since 060f8b6.

@simark: you should no longer feel anxious now.

Please create a new issue if this commit does not fix all the stuff that was discussed here.

**Comment by simark** [comment]
In the event of a spurious network failure, do we retry a few times now? It would make it a bit more robust from the point of view of the user. I could take a look at the code but I prefer to ask you. I had started #51, if it's still relevant I'll update it.

**Comment by eepp** [comment]
Yes I think #51 could be adapted to the newest version. See `toutv/exceptions.py` for common exceptions; I don't think your `NetworkError` is needed anymore.
